---
title: "Reveiw Questions"
output: html_document
---


* Please Read Chapters 1-3 of Applied 
Predictive Modeling 


# 1.  Do the boston-housing.Rmd assignment
Don't forget to show your works, plots included.



# 2. Algorithms and Functions

When speaking of Machine Learning, there are two functions or algorithms involved.
Describe and differentiate the algorithms from the function.

Supervised learning: In a supervised learning algorithm, the data is a set of training examples with the associated "correct answers". The algorithm learns to predict the correct answer from this training set. An example of this would be learning to predict whether an email is spam if given a million emails, each of which is labeled as "spam" or "not spam".


Unsupervised learning: In an unsupervised learning algorithm, the algorithm can find trends in the data it is given, without looking for some specific "correct answer". Examples of unsupervised learning algorithms involve clustering (grouping similar data points) or anomaly detection (detecting unusual data points in a data set).



# 2. RMSE and MAE

Why is RMSE preferrable to MAE? 
The square root of the average is taken. Since the errors are squared before they are averaged, the RMSE gives a relatively high weight to large errors. This means the RMSE is most useful when large errors are particularly undesirable.

When is MAE better? 
It measures accuracy for continuous variables, as the MAE measures the average magnitude of the errors in a set of forecasts, without considering their direction. 




